<!--
/**
 * Copyright 2016 Matthew R. Miller via Classy Geeks llc. All Rights Reserved
 * http://classygeeks.com
 * MIT License:
 * http://opensource.org/licenses/MIT
 */
-->


<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3 class="icon-head head-sales-order"><?php echo(Mage::helper('mailman')->__('Subject:')); ?> <?php echo(Mage::registry('message')->getSubject()); ?></h3></td>
            <td class="a-right">
	            <form id="mailman_view_form" name="mailman_view_form" method="post" action="<?php echo($this->getUrl('*/*/requeue')) ?>">
                    <button class="scalable save" type="submit"><span><?php echo(Mage::helper('mailman')->__('Re-Queue Message For Sending')); ?></span></button>
		            <input name="form_key" type="hidden" value="<?php echo(Mage::getSingleton('core/session')->getFormKey()); ?>" />
					<input name="id" type="hidden" value="<?php echo(Mage::registry('message')->getMessageId()); ?>" />
				</form>
	            &nbsp;&nbsp;
	            <button class="scalable save" type="button" onclick="window.open('<?php echo($this->getUrl('*/*/body/', array('id' => Mage::registry('message')->getMessageId()))) ?>', '_blank');"><span>View Body</span></button>
            </td>
        </tr>
    </table>
</div>

<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend">Message Details</h4>

    <fieldset>
        <table cellspacing="0" class="form-list">

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Id')); ?></td>
                <td class="value"><?php echo(Mage::registry('message')->getId()); ?></td>
            </tr>

            <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Status')); ?></td>
                <td class="value"><?php echo(Mage::helper('mailman')->convertStatusId(Mage::registry('message')->getStatusId())); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('From')); ?></td>
                <td class="value"><?php echo(Mage::helper('mailman')->formatEmails(Mage::registry('message')->getEmailFrom())); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Reply To')); ?></td>
                <td class="value"><?php echo(Mage::registry('message')->getEmailReply()); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Return Path')); ?></td>
                <td class="value"><?php echo(Mage::registry('message')->getEmailReturnPath()); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('To')); ?></td>
                <td class="value"><?php echo(Mage::helper('mailman')->formatEmails(Mage::registry('message')->getEmailTo())); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Cc')); ?></td>
                <td class="value"><?php echo(Mage::helper('mailman')->formatEmails(Mage::registry('message')->getEmailCc())); ?></td>
            </tr>

	        <tr>
                <td class="label"><?php echo(Mage::helper('mailman')->__('Bcc')); ?></td>
                <td class="value"><?php echo(Mage::helper('mailman')->formatEmails(Mage::registry('message')->getEmailBcc())); ?></td>
            </tr>

        </table>
    </fieldset>


</div>

<?php if (Mage::registry('attachments')->count()): ?>

	<div class="entry-edit">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo(Mage::helper('mailman')->__('Attachments')); ?></h4>

		<?php foreach (Mage::registry('attachments') as $oAttachment) : ?>

		    <fieldset>
		        <table cellspacing="0" class="form-list">
		            <tr>
		                <td class="label"><?php echo($oAttachment->getFileName()); ?></td>
		                <td class="value"><button class="scalable save" type="button" onclick="window.location='<?php echo($this->getUrl('*/*/attachment/', array('id' => $oAttachment->getAttachmentId()))) ?>';"><span>Download</span></button></td>
		            </tr>
		        </table>
		    </fieldset>

		<?php endforeach; ?>
	</div>

<?php endif; ?>

